var hab_i18n = {
	"ver menos": "ver menos",
	"Estadísticas para los últimos 12 meses": "Estatísticas dos últimos 12 meses",
	"Selecciona un tipo de trabajo": "Selecione um tipo de trabalho",
	"Hay cambios que no han sido guardados, ¿deseas guardarlos?": "Há mudanças que não foram salvas. Quer salvar?",
	"menos": "menos",
	"No es un email válido": "Este e-mail não é válido",
	"Regístrate con Facebook": "Cadastrar com Facebook",
	"Cargando...": "Carregando...",
	"Categoría no válida": "Esta categoria não é válida",
	"Visitas": "Visitas",
	"Introduce al menos {0} caracteres": "Introduzir pelo menos {0} caracteres",
	"Debes rellenar este campo": "Este campo deve ser preenchido",
	"Introduce una fecha válida": "Introduz uma data válida",
	"Este email pertenece a una empresa, por favor introduce otro": "Este e-mail pertence a uma empresa, por favor introduza outro",
	"No introduzcas más de {0} caracteres.": "Não introduza mais de {0} caracteres.",
	"Leer menos": "Ver menos",
	"/proyectos": "/projetos",
	"<span class=\"text-bold\">{count}</span> caracteres para terminar": "<span class=\"text-bold\">{count}</span> caracteres para terminar",
	"Procesando...": "Processando...",
	"Población no válida": "Esta cidade não é válida",
	"Introduce una URL vlida": "Introduza uma URL válida",
	"Enviar mensaje privado a <span></span>": "Enviar mensagem privada para <span></span>",
	"Regístrate con Google": "Cadastrar com Google",
	"Introduce una fecha ISO vlida": "Introduza uma data ISO válida",
	"Iniciar sesión": "Entrar",
	"Has guardado la foto en <a href=\"{album_url}\">el álbum <strong>{album}</strong></a>": "A foto foi guardada no <a href=\"{album_url}\">álbum <strong>{album}</strong></a>",
	"Selecciona una categoría": "Selecione uma categoria",
	"volver": "voltar",
	"¡Bienvenido a habitissimo!": "Bem- vindo ao habitissimo!",
	"¿Estás seguro que quieres eliminar la foto? Esta operación es irreversible": "Tem certeza que quer eliminar a foto? Esta ação não pode ser desfeita",
	"Introduce un nmero vlido": "Introduza um número válido",
	"No disponible": "Não disponível",
	"Lo sentimos, no hemos podido subir tu fichero. Por favor intenta nuevamente en unos segundos.": "Sinto muito! Não foi possível fazer o upload do seu arquivo. Tente novamente em alguns segundos.",
	"Cambiando tamaño...": "Modificando tamanho...",
	"Este campo es obligatorio": "Este campo é obrigatório",
	"40.396764": "-11.609193",
	"Introduce una dirección válida": "Introduz um endereço válido",
	"Valor incorrecto": "Este valor é incorreto",
	"Todas": "Todas",
	"Twitter": "Twitter",
	"Cerrar": "Fechar",
	"Descargar imagen": "Baixar imagem",
	"Introduce una direccin vlida": "Introduza uma direção válida",
	"Veces": "Vezes",
	"No se han encontrado resultados": "Não foram encontrados resultados",
	"¿Deseas regalar este presupuesto a la empresa?": "Quer presentear alguma empresa com este orçamento?",
	"Mostrar toda la descripción": "Mostrar toda a descrição",
	"Compartir": "Compartilhar",
	"Bandeja de entrada": "Caixa de entrada",
	"No se ha podido abrir la conversación": "Não foi possível abrir a conversa",
	"Editar": "Editar",
	"Has guardado la foto en <a href=\"{album_url}\">el lbum <strong>{album}</strong></a>": "Você guardou a foto no <a href=\"{album_url}\">álbum <strong>{album}</strong></a>",
	"{count} caracteres para terminar.": "{count} caracteres para terminar.",
	"Siguiente": "Seguinte",
	"Introduce un número de tarjeta válida": "Introduz um número de cartão válido",
	"Introduce un número válido": "Introduza um número válido",
	"Introduce un nmero de tarjeta vlida": "Introduza um número de cartão válido.",
	"Crear cuenta": "Cadastrar",
	"<p class=\"text-center no-messages\">No hay mensajes nuevos</p>": "<p class=\"text-center no-messages\">Não há novas mensagens</p>",
	"¿No estás registrado en {brand_name}?": "Ainda não está cadastrado no {brand_name}?",
	"Introduce una fecha ISO válida": "Introduz uma data válida",
	"¿A que es genial esta foto?": "Esta foto é genial!",
	"Solo se permiten dígitos": "Só são permitidos dígitos",
	"/marcas/": "/marcas/",
	"Últimos 30 días": "Últimos 30 dias",
	"Selecciona una categora": "Selecione uma categoria",
	"Logotipo": "Logotipo",
	"Puedes inspirarte, resolver tus dudas y encontrar profesionales para tu hogar": "Você pode inspirar-se, resolver suas dúvidas e encontrar profissionais para seu lar.",
	"Introducir presupuesto": "Inserir orçamento",
	"/ofertas/": "/ofertas/",
	"No es un teléfono válido": "Este telefone não é válido",
	"Pinterest": "Pinterest",
	"Introduce una fecha vlida": "Introduza uma data válida",
	"Entra con Facebook": "Entrar com Facebook",
	"Valor no válido": "Este valor não é válido",
	"Página": "Página",
	"Cualquier trabajo de": "Qualquer trabalho de",
	"Mostrar todo": "Mostrar tudo",
	"ver todos": "ver todos",
	"Introduce una URL válida": "Introduz uma URL válida",
	"Solo se aceptan imágenes en formato JPG,PNG,GIF y BMP": "Somente imagens em formato JPG, PNG, GIF e BMP",
	"No es una opción válida": "Esta opção não é válida",
	"Esconder descripcin": "Esconder descrição",
	"¡Bienvenido a {brand_name}!": "Bem-vindo a {brand_name}!",
	"Mostrar toda la descripcin": "Mostrar toda a descrição",
	"Bienvenido a Habitissimo": "Bem-vindo ao Habitissimo",
	"Facebook": "Facebook",
	"Starting upload": "Começando upload do arquivo",
	"Ideas para decorar tu hogar en Habitissimo": "Idéias para decorar seu lar no Habitissimo",
	"Debes aceptar los términos y condiciones": "Os termos e condições devem ser aceitos",
	"Anterior": "Anterior",
	"Necesitamos que entres a tu cuenta o estés registrado para poder guardarla": "Precisamos que você entre na sua conta ou esteja cadastrado para poder guardá-la",
	"¿Eres autónomo o empresa?": "Autônomo ou empresa?",
	"/ofertas": "/ofertas",
	"Estadísticas para los últimos 30 días": "Estatísticas dos últimos 30 dias",
	"Leer más": "Ler mais",
	"Esconder descripción": "Ocultar descrição",
	"Tus imágenes no han sido subidas aún. ¿Deseas continuar subiendo tus imágenes?": "O upload das suas imagens ainda não terminou. Quer continuar?",
	"No introduzcas ms de {0} caracteres.": "Não introduza mais de {0} caracteres.",
	"Crea una cuenta como profesional": "Cadastrar como profissional",
	"Hay mucho por descubrir, entra en tu nueva casa.": "Há muito por descobrir, entre em sua nova casa.",
	"/opiniones": "/opiniões",
	"Solo se permiten dgitos": "Somente se permitem dígitos",
	"Sin opciones": "Sem avaliações",
	"¡Bienvenid@ a habitissimo!": "Bem-vindo ao habitissimo!",
	"Últimos 7 días": "Últimos 7 dias",
	"quitar": "apagar",
	"Zoom in/out": "Zoom",
	"Ests seguro que quieres eliminar la foto? Esta operacin es irreversible": "Tem certeza que você quer eliminar a foto? Esta operação é irreversível",
	"ver más": "Ver mais",
	"Últimos 12 meses": "Últimos 12 meses",
	"/presupuestos": "/orçamentos",
	"Estadísticas para los últimos 7 días": "Estatísticas dos últimos 7 dias",
	"Entra con Google": "Entrar com Google",
	"ver ms": "ver mais",
	"Lo sentimos, no hemos podido subir tu imagen. Por favor intenta nuevamente en unos segundos.": "Sinto muito! Não p foi possível fazer o upload da imagem. Tente novamente em alguns segundos.",
	"Volver": "Voltar",
	"No es un código postal válido": "Este CEP não é válido",
	"Palabra clave": "Palavra-chave",
	"Introduce almenos {0} caracteres": "Introduza pelo menos {0} caracteres",
	"-3.713379": "-51.108398",
	"Regístrate y podrás inspirarte, resolver tus dudas, encontrar profesionales para tu hogar...": "Cadastre-se e inspire-se, resolva dúvidas, encontre profissionais para seu lar...",
	"Cargando": "Carregando",
	"/reformas/": "/reformas/",
	"NaN": "NaN"
}
